api_url: "https://lapis.cov-spectrum.org/open/v2/sample/aggregated"
country: "Switzerland"

wastewater_data_path: "../../data/main/deconvolved.csv"

run_name: "config_ba1"

wastewater_cities:
  - "Zürich (ZH)"
  - "Altenrhein (SG)"
  - "Laupen (BE)"
  - "Lugano (TI)"
  - "Chur (GR)"
  - "Genève (GE)"

variant_list:
  - "B.1.617.2*"
  - "BA.1*"

variants_full:
  - "B.1.617.2*"
  - "BA.1*"

variants_investigated:
  - "BA.1*"

filter:
  start_date: "2021-11-20"
  end_date: "2022-01-01"
  date_range:
    start: "2021-11-27"
    end: "2022-01-01"
  divisions:
    - "Zürich"
    - "Geneva"
    - "Ticino"
    - "Graubünden"
    - "Bern"
    - "Sankt Gallen"
