api_url: "https://lapis.cov-spectrum.org/open/v2/sample/aggregated"
country: "Switzerland"
wastewater_data_path: "../../../LolliPop/lollipop_covvfit/deconvolved.csv"

run_name: "config_ba4ba5"

wastewater_cities:
  - "Zürich (ZH)"
  - "Altenrhein (SG)"
  - "Laupen (BE)"
  - "Lugano (TI)"
  - "Chur (GR)"
  - "Genève (GE)"

variant_list:
  - "B.1.617.2*"
  - "BA.1*"
  - "BA.2*"
  - "BA.4*"
  - "BA.5*"

variants_full:
  - "B.1.617.2*"
  - "BA.1*"
  - "BA.2*"
  - "BA.4*"
  - "BA.5*"

variants_investigated:
  - "BA.1*"
  - "BA.2*"
  - "BA.4*"
  - "BA.5*"

filter:
  start_date: "2021-11-01"
  end_date: "2022-07-31"
  date_range:
    start: "2022-04-01"
    end: "2022-07-31"
  divisions:
    - "Zürich"
    - "Geneva"
    - "Ticino"
    - "Graubünden"
    - "Bern"
    - "Sankt Gallen"
