name: covvfit
channels:
- bioconda
- conda-forge
dependencies:
- arviz=0.16.1
- matplotlib-base=3.8.0
- numpy=1.25.2
- pandas=2.1.2
- pip=23.3.1
- pymc=5.9.1
- pymc-base=5.9.1
- pytensor=2.17.3
- pytensor-base=2.17.3
- pytest=7.4.3
- python=3.10.13
- pyyaml=6.0.1
- scipy=1.11.3
- setuptools=68.2.2
- snakemake=7.32.4
- snakemake-minimal=7.32.4
- xarray=2023.10.1
- xarray-einstats=0.6.0
- yaml=0.2.5

